[build]
  command = "npm run build"
  publish = "dist/my-first-angular-app/browser"

[[redirects]]
  from = "/"
  to = "/board/0"
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200